version: '3'
services:
  libretranslate:
    image: libretranslate/libretranslate:latest
    ports:
      - "5002:5000"
    environment:
      - LT_LOAD_ONLY=en,pt,es,fr,de,it,ja,ko,zh
      - LT_UPDATE_MODELS=true
    volumes:
      - ./libretranslate-data:/home/libretranslate/.local 